trigger:
- main

pool:
 name: pool-test

stages:
- stage:
  jobs:
  - job: BuildPushImage
    steps:

    - task: Docker@2
      inputs:
        containerRegistry: 'DockerR'
        repository: 'azuretest'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
